name: Publish Docker

on:
  push:
    branches:
      - saga
  schedule:
    - cron: "0 0 * * *"

env:
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    strategy:
      matrix:
        ncs_branch:
          - main
          - v1.7-branch
          - v1.6-branch
          - v1.5-branch
          - v1.4-branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          git clone --single-branch --branch ${{ matrix.ncs_branch }} https://github.com/nrfconnect/sdk-nrf nrf
          cd nrf
          docker build -t coderbyheart/fw-nrfconnect-nrf-docker:${{ matrix.ncs_branch }} -f ../Dockerfile .

      - name: Build asset_tracker application
        run: |
          docker run --rm -v ${PWD}/nrf:/workdir/ncs/nrf \
            coderbyheart/fw-nrfconnect-nrf-docker:${{ matrix.ncs_branch }} \
            /bin/bash -c 'cd ncs/nrf/applications/asset_tracker && west build -p always -b nrf9160dk_nrf9160ns'

      - uses: actions/upload-artifact@v2
        with:
          name: asset_tracker-${{ matrix.ncs_branch }}
          path: |
            nrf/applications/asset_tracker_v2/build/merged.hex
            nrf/applications/asset_tracker_v2/build/zephyr/app_update.bin

      - name: Build asset_tracker_v2 application
        # Not available in 1.4, and needs configuration in 1.5
        if: matrix.ncs_branch != 'v1.4-branch' && matrix.ncs_branch != 'v1.5-branch'
        run: |
          docker run --rm -v ${PWD}/nrf:/workdir/ncs/nrf \
            coderbyheart/fw-nrfconnect-nrf-docker:${{ matrix.ncs_branch }} \
            /bin/bash -c 'cd ncs/nrf/applications/asset_tracker_v2 && west build -p always -b nrf9160dk_nrf9160ns'

      - uses: actions/upload-artifact@v2
        if: matrix.ncs_branch != 'v1.4-branch' && matrix.ncs_branch != 'v1.5-branch'
        with:
          name: asset_tracker_v2-${{ matrix.ncs_branch }}
          path: |
            nrf/applications/asset_tracker_v2/build/zephyr/merged.hex
            nrf/applications/asset_tracker_v2/build/zephyr/app_update.bin

      - name: Publish image
        run: |
          cd nrf
          docker login -u coderbyheart -p $DOCKER_PASSWORD
          docker images
          docker push coderbyheart/fw-nrfconnect-nrf-docker:${{ matrix.ncs_branch }}
