name: Verify Dockerfile

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build image
        run: |
          git clone https://github.com/NordicPlayground/fw-nrfconnect-nrf
          cd fw-nrfconnect-nrf
          docker build -t coderbyheart/fw-nrfconnect-nrf-docker -f ../Dockerfile .
      - name: Build asset_tracker application
        run: |
          docker run \
            --rm -v ${PWD}:/workdir/ncs/nrf \
            coderbyheart/fw-nrfconnect-nrf-docker \
            /bin/bash -c 'cd ncs/nrf/applications/asset_tracker; west build -p always -b nrf9160_pca20035ns'
